import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'
import { auth } from '@/auth'
import { AuthProvider } from '@/components/AuthProvider'
import { redirect } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const session = await auth()

    if (!session) {
        redirect('/signin')
    }

    return (
        <html lang='en'>
            <body className={inter.className}>
                <AuthProvider session={session}>
                    {children}
                    <Toaster />
                </AuthProvider>
            </body>
        </html>
    )
}
